# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0004_auto_20171212_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='Avatar'),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
